package com.dianping.poi.datainput.module.dppoi;

import java.util.ArrayList;
import java.util.List;

public class POIPropertyValueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public POIPropertyValueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPropValueIdIsNull() {
            addCriterion("prop_value_id is null");
            return (Criteria) this;
        }

        public Criteria andPropValueIdIsNotNull() {
            addCriterion("prop_value_id is not null");
            return (Criteria) this;
        }

        public Criteria andPropValueIdEqualTo(Integer value) {
            addCriterion("prop_value_id =", value, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdNotEqualTo(Integer value) {
            addCriterion("prop_value_id <>", value, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdGreaterThan(Integer value) {
            addCriterion("prop_value_id >", value, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prop_value_id >=", value, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdLessThan(Integer value) {
            addCriterion("prop_value_id <", value, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdLessThanOrEqualTo(Integer value) {
            addCriterion("prop_value_id <=", value, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdIn(List<Integer> values) {
            addCriterion("prop_value_id in", values, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdNotIn(List<Integer> values) {
            addCriterion("prop_value_id not in", values, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdBetween(Integer value1, Integer value2) {
            addCriterion("prop_value_id between", value1, value2, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prop_value_id not between", value1, value2, "propValueId");
            return (Criteria) this;
        }

        public Criteria andPropValueNameIsNull() {
            addCriterion("prop_value_name is null");
            return (Criteria) this;
        }

        public Criteria andPropValueNameIsNotNull() {
            addCriterion("prop_value_name is not null");
            return (Criteria) this;
        }

        public Criteria andPropValueNameEqualTo(String value) {
            addCriterion("prop_value_name =", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameNotEqualTo(String value) {
            addCriterion("prop_value_name <>", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameGreaterThan(String value) {
            addCriterion("prop_value_name >", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameGreaterThanOrEqualTo(String value) {
            addCriterion("prop_value_name >=", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameLessThan(String value) {
            addCriterion("prop_value_name <", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameLessThanOrEqualTo(String value) {
            addCriterion("prop_value_name <=", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameLike(String value) {
            addCriterion("prop_value_name like", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameNotLike(String value) {
            addCriterion("prop_value_name not like", value, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameIn(List<String> values) {
            addCriterion("prop_value_name in", values, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameNotIn(List<String> values) {
            addCriterion("prop_value_name not in", values, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameBetween(String value1, String value2) {
            addCriterion("prop_value_name between", value1, value2, "propValueName");
            return (Criteria) this;
        }

        public Criteria andPropValueNameNotBetween(String value1, String value2) {
            addCriterion("prop_value_name not between", value1, value2, "propValueName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 22 15:13:51 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}