package com.dianping.poi.datainput.module.dppoi;

public class POIProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_Property.prop_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Integer propId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_Property.prop_name
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private String propName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_Property.parent_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_Property.is_global
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Boolean isGlobal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_Property.prop_id
     *
     * @return the value of POI_Property.prop_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Integer getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_Property.prop_id
     *
     * @param propId the value for POI_Property.prop_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_Property.prop_name
     *
     * @return the value of POI_Property.prop_name
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public String getPropName() {
        return propName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_Property.prop_name
     *
     * @param propName the value for POI_Property.prop_name
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setPropName(String propName) {
        this.propName = propName == null ? null : propName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_Property.parent_id
     *
     * @return the value of POI_Property.parent_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_Property.parent_id
     *
     * @param parentId the value for POI_Property.parent_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_Property.is_global
     *
     * @return the value of POI_Property.is_global
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Boolean getIsGlobal() {
        return isGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_Property.is_global
     *
     * @param isGlobal the value for POI_Property.is_global
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setIsGlobal(Boolean isGlobal) {
        this.isGlobal = isGlobal;
    }
}