package com.dianping.poi.datainput.module.dppoi;

public class POIPropertyValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_PropertyValue.prop_value_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Integer propValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_PropertyValue.prop_value_name
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private String propValueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_PropertyValue.prop_value_id
     *
     * @return the value of POI_PropertyValue.prop_value_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Integer getPropValueId() {
        return propValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_PropertyValue.prop_value_id
     *
     * @param propValueId the value for POI_PropertyValue.prop_value_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setPropValueId(Integer propValueId) {
        this.propValueId = propValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_PropertyValue.prop_value_name
     *
     * @return the value of POI_PropertyValue.prop_value_name
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public String getPropValueName() {
        return propValueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_PropertyValue.prop_value_name
     *
     * @param propValueName the value for POI_PropertyValue.prop_value_name
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setPropValueName(String propValueName) {
        this.propValueName = propValueName == null ? null : propValueName.trim();
    }
}