package com.dianping.poi.datainput.module.dppoi;

public class POIPropMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_PropMapping.category_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_PropMapping.prop_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Integer propId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POI_PropMapping.prop_value_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    private Integer propValueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_PropMapping.category_id
     *
     * @return the value of POI_PropMapping.category_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_PropMapping.category_id
     *
     * @param categoryId the value for POI_PropMapping.category_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_PropMapping.prop_id
     *
     * @return the value of POI_PropMapping.prop_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Integer getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_PropMapping.prop_id
     *
     * @param propId the value for POI_PropMapping.prop_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POI_PropMapping.prop_value_id
     *
     * @return the value of POI_PropMapping.prop_value_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public Integer getPropValueId() {
        return propValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POI_PropMapping.prop_value_id
     *
     * @param propValueId the value for POI_PropMapping.prop_value_id
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    public void setPropValueId(Integer propValueId) {
        this.propValueId = propValueId;
    }
}