package com.dianping.poi.datainput.module.dppoi;

public class TestUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.id
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.username
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.userage
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    private Integer userage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.useraddress
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    private String useraddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.id
     *
     * @return the value of test_user.id
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.id
     *
     * @param id the value for test_user.id
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.username
     *
     * @return the value of test_user.username
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.username
     *
     * @param username the value for test_user.username
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.userage
     *
     * @return the value of test_user.userage
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public Integer getUserage() {
        return userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.userage
     *
     * @param userage the value for test_user.userage
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public void setUserage(Integer userage) {
        this.userage = userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.useraddress
     *
     * @return the value of test_user.useraddress
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.useraddress
     *
     * @param useraddress the value for test_user.useraddress
     *
     * @mbggenerated Fri May 01 18:57:20 CST 2015
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress == null ? null : useraddress.trim();
    }

	@Override
	public String toString() {
		return "TestUser [id=" + id + ", username=" + username + ", userage="
				+ userage + ", useraddress=" + useraddress + "]";
	}
    
    
}