package com.dianping.poi.datainput.module.dppoi;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.ID
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.user_id
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.tree_id
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    private Integer treeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.ID
     *
     * @return the value of USER_ROLE.ID
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.ID
     *
     * @param id the value for USER_ROLE.ID
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.user_id
     *
     * @return the value of USER_ROLE.user_id
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.user_id
     *
     * @param userId the value for USER_ROLE.user_id
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.tree_id
     *
     * @return the value of USER_ROLE.tree_id
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    public Integer getTreeId() {
        return treeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.tree_id
     *
     * @param treeId the value for USER_ROLE.tree_id
     *
     * @mbggenerated Sat Apr 25 21:50:18 CST 2015
     */
    public void setTreeId(Integer treeId) {
        this.treeId = treeId;
    }
}