package com.dianping.poi.datainput.mapper.dppoi;

import com.dianping.poi.datainput.module.dppoi.POICategory;
import com.dianping.poi.datainput.module.dppoi.POICategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface POICategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int countByExample(POICategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int deleteByExample(POICategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int insert(POICategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int insertSelective(POICategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    List<POICategory> selectByExample(POICategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    POICategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") POICategory record, @Param("example") POICategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByExample(@Param("record") POICategory record, @Param("example") POICategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByPrimaryKeySelective(POICategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_Category
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByPrimaryKey(POICategory record);
    
    POICategory getCategorysByProID(int proID);
}