package com.dianping.poi.datainput.mapper.dppoi;

import com.dianping.poi.datainput.module.dppoi.POIPropMapping;
import com.dianping.poi.datainput.module.dppoi.POIPropMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface POIPropMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int countByExample(POIPropMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int deleteByExample(POIPropMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int insert(POIPropMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int insertSelective(POIPropMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    List<POIPropMapping> selectByExample(POIPropMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") POIPropMapping record, @Param("example") POIPropMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropMapping
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByExample(@Param("record") POIPropMapping record, @Param("example") POIPropMappingExample example);
}