package com.dianping.poi.datainput.mapper.dppoi;

import com.dianping.poi.datainput.module.dppoi.POIPropertyValue;
import com.dianping.poi.datainput.module.dppoi.POIPropertyValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface POIPropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int countByExample(POIPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int deleteByExample(POIPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int insert(POIPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int insertSelective(POIPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    List<POIPropertyValue> selectByExample(POIPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") POIPropertyValue record, @Param("example") POIPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POI_PropertyValue
     *
     * @mbggenerated Wed Apr 22 15:13:51 CST 2015
     */
    int updateByExample(@Param("record") POIPropertyValue record, @Param("example") POIPropertyValueExample example);
}