package com.dianping.poi.datainput.mapper.dppoi;

import com.dianping.poi.datainput.module.dppoi.TBTree;
import com.dianping.poi.datainput.module.dppoi.TBTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int countByExample(TBTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int deleteByExample(TBTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int insert(TBTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int insertSelective(TBTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    List<TBTree> selectByExample(TBTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    TBTree selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") TBTree record, @Param("example") TBTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int updateByExample(@Param("record") TBTree record, @Param("example") TBTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int updateByPrimaryKeySelective(TBTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TREE
     *
     * @mbggenerated Sat Apr 25 16:44:42 CST 2015
     */
    int updateByPrimaryKey(TBTree record);
    
    List<TBTree> selectAll();
}